"""
事件系统 v2 - 基于股市随机事件.docx 完全重建
==============================================
包含三大类事件：
1. 固定时间线事件 (SCHEDULED_EVENTS) - 每学期固定时间点触发
2. 每日随机事件池 (RANDOM_EVENT_POOL) - 每天随机抽取1-2个
3. 因果关系链 (CAUSE_CHAINS) - 起因→经过(1-3天后)→影响

股票映射 (24只):
  科创智造: om-brain, computer, super-sci, aero-model, robot
  文艺传媒: reporter, xuanling, mayfly-band, 181-band, percussion, shanghai
  思辨学术: mun, debate
  校园体育: basketball, football, badminton, curling
  班级股:   class1-class7
"""
from stock_data import STOCKS

ALL_STOCKS = list(STOCKS.keys())
CLUB_STOCKS = list(ALL_STOCKS)  # 全部是社团股
CLASS_STOCKS = []  # 班级股已删除，事件中涉及班级股均为中立事件（无影响）

# 分板块股票列表
STOCKS_KEJI = ["om-brain", "computer", "super-sci", "aero-model", "robot"]
STOCKS_WENYI = ["reporter", "xuanling", "mayfly-band", "181-band", "percussion", "shanghai"]
STOCKS_SIBIAN = ["mun", "debate"]
STOCKS_TIYU = ["basketball", "football", "badminton", "curling"]


# ============================================================
# 第一部分：固定时间线事件（每学期定期发生）
# ============================================================
# 6个学期 × 100天 = 600天总教学日
# 事件安排在每学期的固定时间点触发
# ============================================================

SCHEDULED_EVENTS = [
    # ==================== 高一上 (Day 1-100) ====================
    {
        "trigger_day": 1,
        "title": "🏫 新学期开学 · 社团招新大战",
        "description": "新学期伊始！各大社团使出浑身解数招揽新生，热门社团展位前排起长龙。这是每个社团一年中最重要的招新时刻！",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "bullish",
        "impact_min": 0.03, "impact_max": 0.12,
        "duration_days": 5,
        "schedule_type": "每学期开学",
    },
    {
        "trigger_day": 5,
        "title": "📋 社团招新结果公布",
        "description": "各大社团招新名单正式公布！有的社团招得新生爆满，有的门可罗雀。新生分配结果直接影响社团未来一年的发展。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "mixed",
        "impact_min": -0.08, "impact_max": 0.18,
        "duration_days": 4,
        "schedule_type": "每学期招新后",
    },
    {
        "trigger_day": 20,
        "title": "🏆 首次流动红旗评选",
        "description": "本学期首次流动红旗评选结果出炉！获奖班级士气大振，未获奖的班级也在暗中追赶。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.08, "impact_max": 0.20,
        "duration_days": 4,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 30,
        "title": "🏃 秋季运动会开幕",
        "description": "一年一度的秋季运动会正式开幕！运动员们在赛场上奋力拼搏，体育类社团和各班迎来高光时刻。",
        "stocks_affected": STOCKS_TIYU + CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.05, "impact_max": 0.22,
        "duration_days": 4,
        "schedule_type": "每学期运动会",
    },
    {
        "trigger_day": 40,
        "title": "🏆 第二次流动红旗评选",
        "description": "月度流动红旗结果公布！获奖班级继续保持领先，竞争进入白热化。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.06, "impact_max": 0.18,
        "duration_days": 3,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 45,
        "title": "📝 期中考试周",
        "description": "期中考试来临，同学们埋头复习。社团活动暂停，市场交易情绪较为低迷。部分社团受影响明显。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "bearish",
        "impact_min": -0.10, "impact_max": -0.02,
        "duration_days": 5,
        "schedule_type": "每学期期中考试",
    },
    {
        "trigger_day": 55,
        "title": "📊 期中成绩公布 · 学风评比",
        "description": "期中考试成绩出炉，各班排名牵动人心。成绩优异的班级士气大振，学风评比结果同步发布。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.12, "impact_max": 0.22,
        "duration_days": 4,
        "schedule_type": "期中后",
    },
    {
        "trigger_day": 60,
        "title": "🏆 第三次流动红旗评选",
        "description": "本月流动红旗揭晓。累计获奖次数最多的班级开始领跑，竞争愈发激烈。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.06, "impact_max": 0.16,
        "duration_days": 3,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 75,
        "title": "🎄 校园艺术节",
        "description": "校园艺术节盛大举办！音乐、舞蹈、戏剧轮番上演，文艺类社团成为全场焦点。",
        "stocks_affected": STOCKS_WENYI,
        "impact_type": "bullish",
        "impact_min": 0.08, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "每学期艺术节",
    },
    {
        "trigger_day": 85,
        "title": "🏆 学期末流动红旗总评",
        "description": "本学期最后一次流动红旗评选！谁将成为学期最佳班级？荣誉之战进入最终回合！",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.10, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "学期末流动红旗",
    },
    {
        "trigger_day": 90,
        "title": "📚 期末考试周",
        "description": "期末考试全面展开，所有社团活动暂停。考试成绩将直接影响班级股价格走势。",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "bearish",
        "impact_min": -0.08, "impact_max": -0.02,
        "duration_days": 5,
        "schedule_type": "每学期期末考试",
    },

    # ==================== 高一下 (Day 101-200) ====================
    {
        "trigger_day": 106,
        "title": "🌸 新学期开学回暖 · 社团春季招新",
        "description": "寒假归来，校园重新充满活力。社团春季补充招新开始，上学期表现优异的社团吸引了更多关注。",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "bullish",
        "impact_min": 0.03, "impact_max": 0.10,
        "duration_days": 3,
        "schedule_type": "每学期开学",
    },
    {
        "trigger_day": 120,
        "title": "🏆 流动红旗评选（高一下·第一次）",
        "description": "新学期首次流动红旗评选，经过一个学期的磨合，各班差距逐渐拉大。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.08, "impact_max": 0.20,
        "duration_days": 4,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 130,
        "title": "🧪 科技节开幕",
        "description": "校园科技节拉开帷幕！机器人社、超科学社、计算机社的展品吸引了众多目光。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bullish",
        "impact_min": 0.08, "impact_max": 0.22,
        "duration_days": 5,
        "schedule_type": "每学期科技节",
    },
    {
        "trigger_day": 140,
        "title": "🏆 流动红旗评选（高一下·第二次）",
        "description": "月度流动红旗评比继续，优秀班级持续领跑。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.06, "impact_max": 0.16,
        "duration_days": 3,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 145,
        "title": "📝 下学期期中考试",
        "description": "高一下学期期中考试！课程难度加大，同学们面临新的挑战。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "bearish",
        "impact_min": -0.12, "impact_max": -0.03,
        "duration_days": 5,
        "schedule_type": "每学期期中考试",
    },
    {
        "trigger_day": 160,
        "title": "🎤 校园歌手大赛",
        "description": "校园歌手大赛火热进行中！两大乐队蜉蝣天空和181的成员纷纷参赛，现场气氛热烈。",
        "stocks_affected": ["mayfly-band", "181-band", "percussion"],
        "impact_type": "bullish",
        "impact_min": 0.10, "impact_max": 0.28,
        "duration_days": 4,
        "schedule_type": "每学期文娱赛事",
    },
    {
        "trigger_day": 175,
        "title": "🏆 学期末流动红旗总评（高一下）",
        "description": "高一下学期流动红旗最终排名揭晓，各班级荣誉感爆棚！",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.10, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "学期末流动红旗",
    },
    {
        "trigger_day": 185,
        "title": "🎓 高三毕业季 · 社团换届",
        "description": "高三学长学姐即将毕业，社团迎来换届。新任社长即将产生，各社团未来走向充满变数。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN,
        "impact_type": "mixed",
        "impact_min": -0.15, "impact_max": 0.25,
        "duration_days": 6,
        "schedule_type": "每学年社团换届",
    },
    {
        "trigger_day": 190,
        "title": "📚 下学期期末考试",
        "description": "高一学年最后一次考试！成绩将影响分班和社团资格。",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "bearish",
        "impact_min": -0.08, "impact_max": -0.02,
        "duration_days": 5,
        "schedule_type": "每学期期末考试",
    },

    # ==================== 高二上 (Day 201-300) ====================
    {
        "trigger_day": 201,
        "title": "🏫 高二开学 · 社团新社长上任",
        "description": "高二开始！各大社团新社长走马上任。有的锐意改革，有的稳扎稳打。新社长将为社团带来怎样的变化？",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "mixed",
        "impact_min": -0.12, "impact_max": 0.15,
        "duration_days": 6,
        "schedule_type": "每学期开学+换届",
    },
    {
        "trigger_day": 220,
        "title": "🏆 流动红旗评选（高二上·第一次）",
        "description": "新学期流动红旗重新洗牌！上一学年的积累在高二开始体现。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.08, "impact_max": 0.20,
        "duration_days": 4,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 230,
        "title": "🏃 秋季运动会（高二主场）",
        "description": "高二年级成为运动会主力军！各班为了荣誉全力拼搏，体育社团再次迎来爆发期。",
        "stocks_affected": STOCKS_TIYU + CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.03, "impact_max": 0.22,
        "duration_days": 4,
        "schedule_type": "每学期运动会",
    },
    {
        "trigger_day": 245,
        "title": "📝 高二上期中考试 · 会考预演",
        "description": "高二期中考试难度提升，同时是明年会考的预演。学业压力开始影响社团活动。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "bearish",
        "impact_min": -0.14, "impact_max": -0.04,
        "duration_days": 5,
        "schedule_type": "每学期期中考试",
    },
    {
        "trigger_day": 280,
        "title": "🏆 学期流动红旗总评（高二上）",
        "description": "累计本学期流动红旗获得次数，综合评选最佳班级。荣誉之战进入白热化！",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.10, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "学期末流动红旗",
    },

    # ==================== 高二下 (Day 301-400) ====================
    {
        "trigger_day": 306,
        "title": "🌸 高二下开学 · 学业压力初现",
        "description": "高二下是承上启下的关键学期。学业压力和社团活动开始出现平衡难题，但社团活力不减。",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.05, "impact_max": 0.08,
        "duration_days": 3,
        "schedule_type": "每学期开学",
    },
    {
        "trigger_day": 320,
        "title": "🏆 流动红旗评选（高二下·第一次）",
        "description": "本学期首轮流动红旗。经过一年多的竞争，强弱格局逐渐明朗。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.06, "impact_max": 0.18,
        "duration_days": 4,
        "schedule_type": "每月流动红旗",
    },
    {
        "trigger_day": 330,
        "title": "📚 学业水平考试（会考）",
        "description": "高二会考来临！紧张氛围笼罩校园。大多数股票承压，社团活动大幅缩减。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "bearish",
        "impact_min": -0.15, "impact_max": -0.05,
        "duration_days": 6,
        "schedule_type": "高二会考",
    },
    {
        "trigger_day": 345,
        "title": "📊 会考成绩公布",
        "description": "会考成绩出炉！各班级通过率成为新焦点，大家开始认真思考高考方向。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.15, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "会考后",
    },
    {
        "trigger_day": 360,
        "title": "🎭 校园戏剧节",
        "description": "校园戏剧节精彩纷呈！悬铃影社大放异彩，各班精心准备的剧目轮番上演。",
        "stocks_affected": ["xuanling", "shanghai"] + CLASS_STOCKS,
        "impact_type": "bullish",
        "impact_min": 0.05, "impact_max": 0.22,
        "duration_days": 5,
        "schedule_type": "每学期文艺活动",
    },

    # ==================== 高三上 (Day 401-500) ====================
    {
        "trigger_day": 405,
        "title": "📖 高三誓师大会",
        "description": "高三年级誓师大会隆重举行！全体高三学子宣誓冲刺高考，班级凝聚力达到顶峰。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "bullish",
        "impact_min": 0.10, "impact_max": 0.25,
        "duration_days": 4,
        "schedule_type": "高三誓师",
    },
    {
        "trigger_day": 425,
        "title": "🏆 流动红旗最终评选（高三）",
        "description": "高三年级最后一次流动红旗评选。三年来的班级荣誉之争即将画上句号。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.12, "impact_max": 0.28,
        "duration_days": 5,
        "schedule_type": "高三流动红旗",
    },
    {
        "trigger_day": 440,
        "title": "📝 高三第一次模考",
        "description": "首次模拟考试成绩公布！各班级表现不一，成绩优异的班级士气大振。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.20, "impact_max": 0.25,
        "duration_days": 5,
        "schedule_type": "高三模考",
    },
    {
        "trigger_day": 470,
        "title": "🏃 最后一次运动会（高三）",
        "description": "高三学生最后一次参加运动会，不留遗憾！体育社团和各班倾尽全力，赛场气氛达到三年顶峰。",
        "stocks_affected": STOCKS_TIYU + CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.05, "impact_max": 0.25,
        "duration_days": 4,
        "schedule_type": "每学期运动会",
    },
    {
        "trigger_day": 490,
        "title": "📊 高三第二次模考",
        "description": "第二次模考！距离高考越来越近，成绩波动牵动每一位学生和家长的心。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.18, "impact_max": 0.22,
        "duration_days": 5,
        "schedule_type": "高三模考",
    },

    # ==================== 高三下 (Day 501-600) ====================
    {
        "trigger_day": 510,
        "title": "📊 区一模成绩公布",
        "description": "全区统一一模成绩出炉，各班级排名牵动人心。成绩优异的班级股票飙升！",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.25, "impact_max": 0.30,
        "duration_days": 5,
        "schedule_type": "高三一模",
    },
    {
        "trigger_day": 530,
        "title": "📝 高三二模考试",
        "description": "第二次全区模考，这是高考前最后一次大型练兵机会。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.15, "impact_max": 0.20,
        "duration_days": 4,
        "schedule_type": "高三二模",
    },
    {
        "trigger_day": 540,
        "title": "💯 百日誓师",
        "description": "距离高考100天！整个高三年级进入冲刺阶段，班级凝聚力空前高涨。",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "bullish",
        "impact_min": 0.05, "impact_max": 0.15,
        "duration_days": 3,
        "schedule_type": "百日誓师",
    },
    {
        "trigger_day": 570,
        "title": "🎯 高考冲刺 · 社团停摆",
        "description": "高考进入最后冲刺，所有社团活动全面暂停。社团类股票缺乏交易催化剂。",
        "stocks_affected": STOCKS_KEJI + STOCKS_WENYI + STOCKS_SIBIAN + STOCKS_TIYU,
        "impact_type": "bearish",
        "impact_min": -0.10, "impact_max": -0.02,
        "duration_days": 10,
        "schedule_type": "高考冲刺",
    },
    {
        "trigger_day": 590,
        "title": "🎓 高考放榜！",
        "description": "三年磨一剑，高考成绩终于公布！各班级表现天差地别，股票价格剧烈震荡！这是最后的狂欢！",
        "stocks_affected": CLASS_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.30, "impact_max": 0.45,
        "duration_days": 5,
        "schedule_type": "高考放榜",
    },
    {
        "trigger_day": 598,
        "title": "🎉 毕业典礼 · 游戏即将结束",
        "description": "毕业典礼盛大举行，三年的校园证券交易所之旅即将画上句号。感谢你的参与！",
        "stocks_affected": ALL_STOCKS,
        "impact_type": "mixed",
        "impact_min": -0.20, "impact_max": 0.30,
        "duration_days": 2,
        "schedule_type": "毕业",
    },
]


# ============================================================
# 第二部分：每日随机事件池（200+事件，每天随机抽取）
# ============================================================
# 事件分为四类板块专属事件 + 通用宏观事件
# 同一存档中每个事件最多触发一次
# ============================================================

RANDOM_EVENT_POOL = [
    # ========== 科创智造板块 (keji_001 - keji_050) ==========
    {
        "id": "keji_001",
        "title": "🏆 OM社区域创新大赛获专项奖金",
        "description": "黄浦区教育局加码科创赛事扶持，OM社作为种子队伍获得万元团体奖金，扩招20名新生，购入大量搭建耗材。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.25,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_002",
        "title": "⚠️ 机器人社VEX芯片供应链延迟",
        "description": "海外芯片物流拥堵，V5主控设备延迟交付，机器人社自动程序训练被迫停滞。航模社暂时分流部分实验室场地。",
        "stocks_affected": ["robot", "aero-model"],
        "impact_type": "mixed", "impact_min": -0.16, "impact_max": 0.07,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_003",
        "title": "🚗 超科学社获独立实训车间",
        "description": "教育局发布智能驾驶培育政策，向明获批专项基建资金，超科学社拥有专属调试车间，增设智能小车挑战赛。",
        "stocks_affected": ["super-sci"] + STOCKS_KEJI,
        "impact_type": "bullish", "impact_min": 0.05, "impact_max": 0.30,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_004",
        "title": "⚠️ 计算机社竞赛指导老师调离",
        "description": "计算机社金牌竞赛指导老师工作调动，奥赛训练暂停两周，报名人数减半，核心社员流失。",
        "stocks_affected": ["computer", "om-brain", "robot"],
        "impact_type": "mixed", "impact_min": -0.21, "impact_max": 0.06,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_005",
        "title": "🏆 航模社全国锦标赛团体金奖",
        "description": "全国航模锦标赛，向明航模社自主改装滑翔机获高中组团体金奖！器材采购翻倍，新生报名人数翻倍。",
        "stocks_affected": ["aero-model"] + STOCKS_KEJI,
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.35,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_006",
        "title": "⚠️ 线下科创赛事全部取消改为线上",
        "description": "全市校园活动管控，线下搭建类赛事全部取消。OM、航模、机器人社实操备赛作废，仅计算机社线上竞赛不受影响。",
        "stocks_affected": ["computer"] + ["om-brain", "robot", "aero-model", "super-sci"],
        "impact_type": "mixed", "impact_min": -0.15, "impact_max": 0.13,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_007",
        "title": "💡 OM社创意装置获市级专利",
        "description": "OM社长期题道具设计成功申请青少年实用新型专利，获区教育局专利培育补贴，吸引理科特长生加入。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.27,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_008",
        "title": "⚠️ 超科学社电路短路烧毁控制板",
        "description": "实训车间线路老化短路，智能小车核心控制板批量损毁，距离市级比赛仅剩10天！",
        "stocks_affected": ["super-sci", "robot"],
        "impact_type": "mixed", "impact_min": -0.18, "impact_max": 0.05,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_009",
        "title": "🤖 机器人社与交大实验室达成共建",
        "description": "上海交大机电学院导师固定入校为VEX战队提供技术辅导，国赛夺冠预期大幅提高。",
        "stocks_affected": ["robot"] + STOCKS_KEJI,
        "impact_type": "bullish", "impact_min": 0.10, "impact_max": 0.32,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_010",
        "title": "⚠️ 航模社操场施工封闭3个月",
        "description": "校内操场翻新工程开工，航模户外试飞场地封闭，仅能室内静态组装，市级赛事备赛进度滞后。",
        "stocks_affected": ["aero-model", "om-brain"],
        "impact_type": "mixed", "impact_min": -0.14, "impact_max": 0.04,
        "duration_days": 6,
        "block": "科创",
    },
    {
        "id": "keji_011",
        "title": "💻 计算机社开发校园管理小程序",
        "description": "计算机社自主研发社团活动管理小程序，校方采购全校推广，社团获得项目营收，知名度大幅提升。",
        "stocks_affected": ["computer"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.24,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_012",
        "title": "📋 OM社材料成本全额报销",
        "description": "市教委出台科创赛事扶持政策，参赛耗材费用全额报销，OM社大幅扩充道具规模，作品质量提升。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.12, "impact_max": 0.19,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_013",
        "title": "⚠️ 机器人社编程队长转学离校",
        "description": "高二VEX战队主力编程队长转学，自动程序开发停滞，国赛排名预期下调。计算机社吸纳流失社员。",
        "stocks_affected": ["robot", "computer"],
        "impact_type": "mixed", "impact_min": -0.23, "impact_max": 0.08,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_014",
        "title": "🏆 超科学社承办区级公开赛",
        "description": "黄浦区教育局选定向明承办区级智能小车赛事，拨付场地奖品专项经费，社团曝光度大幅提升。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.26,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_015",
        "title": "📸 航模社航拍作品获全市金奖",
        "description": "航模社航拍校园纪录片参与市级影像赛事拿下科创赛道金奖，新增航拍专项器材采购额度。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.21,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_016",
        "title": "⚠️ 科创经费整体缩减30%",
        "description": "学校年度财政收紧，科创板块统一压缩采购经费，器材耗材采购全部减半，全板块估值下行。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bearish", "impact_min": -0.12, "impact_max": -0.07,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_017",
        "title": "🤝 OM社与计算机社联合开发控制系统",
        "description": "OM长期题需要自动液压控制装置，联动计算机社编写程序，两大社团资源互通共享经费与实验室。",
        "stocks_affected": ["om-brain", "computer"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.12,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_018",
        "title": "⚠️ 超科学社市级初赛传感器故障淘汰",
        "description": "市级智能小车初赛车辆传感器故障，连续两年未晋级复赛，社员士气低迷退社潮涌现。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bearish", "impact_min": -0.25, "impact_max": -0.15,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_019",
        "title": "🎓 航模社引进专业航空教练",
        "description": "学校聘请航空高校专业教师担任外聘教练，开设进阶飞行训练课程，参赛获奖概率大幅提高。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.28,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_020",
        "title": "⚠️ VEX新赛季规则大改",
        "description": "VEX官方发布全新赛季规则，现有机械结构全部作废需从零搭建，备赛成本翻倍。",
        "stocks_affected": ["robot", "om-brain"],
        "impact_type": "mixed", "impact_min": -0.17, "impact_max": 0.05,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_021",
        "title": "🏆 计算机社信息奥赛全员晋级省赛",
        "description": "计算机社奥赛集训队全员通过市级初赛晋级省级联赛，创下社团历史最佳战绩！",
        "stocks_affected": ["computer"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.31,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_022",
        "title": "📦 OM社道具材料库存耗尽",
        "description": "OM社常规校内科普活动耗材采购延期，材料库存清零暂停体验活动，校内曝光度下降。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bearish", "impact_min": -0.09, "impact_max": -0.04,
        "duration_days": 3,
        "block": "科创",
    },
    {
        "id": "keji_023",
        "title": "🤝 超科学社与机器人社共享实训车间",
        "description": "校方整合科创实验室资源，两大社团分时段共用大型调试场地，训练时长同步增加。",
        "stocks_affected": ["super-sci", "robot"],
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.10,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_024",
        "title": "⚠️ 航模社穿越机撞伤绿植被限制飞行",
        "description": "社员试飞穿越机失控冲撞校园树木，校方出台管控，大功率无人机仅允许周末限定时段试飞。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bearish", "impact_min": -0.13, "impact_max": -0.08,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_025",
        "title": "🎪 科创五大社团联合成果展",
        "description": "黄浦区选定向明举办全区科创社团成果展，五大科创社团全部设展台，下学年招新预期翻倍。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.18,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_026",
        "title": "⚠️ 计算机社编程教室电脑老化卡顿",
        "description": "编程教室台式机使用超8年运行软件卡顿，更新经费未获批，奥赛备赛质量下滑。",
        "stocks_affected": ["computer"],
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.10,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_027",
        "title": "🎭 OM社创意装置全市美育节展演",
        "description": "OM融合艺术与机械的道具方案被选中作为全市科创节开场展演节目，获市级宣传资源。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.23,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_028",
        "title": "⚠️ 机器人社核心搭建队员出国交流",
        "description": "VEX战队主力机械搭建队员参与国际研学离校半年，零部件组装迭代停滞。",
        "stocks_affected": ["robot"],
        "impact_type": "bearish", "impact_min": -0.19, "impact_max": -0.12,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_029",
        "title": "✈️ 航模社刷新全市高中航模续航纪录",
        "description": "社员自主优化机身轻量化结构，自制滑翔机续航远超同类参赛机型，获批专项研发资金。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.25,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_030",
        "title": "⚠️ 智能小车赛前临时增加难度关卡",
        "description": "市级赛事赛前3天新增复杂避障关卡，社团程序未做对应调试，车辆通过率大幅下降。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bearish", "impact_min": -0.15, "impact_max": -0.09,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_031",
        "title": "🐍 计算机社开设全校Python公开课",
        "description": "计算机社每周开设公益编程公开课面向零基础学生，社团人数扩充40%，校方追加维护经费。",
        "stocks_affected": ["computer"],
        "impact_type": "bullish", "impact_min": 0.10, "impact_max": 0.14,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_032",
        "title": "🤝 OM社与航模社联合创作航空工坊",
        "description": "两大科创社团合作航空主题创新项目，共享搭建材料和3D打印设备，双双获得课题补贴。",
        "stocks_affected": ["om-brain", "aero-model"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.11,
        "duration_days": 3,
        "block": "科创",
    },
    {
        "id": "keji_033",
        "title": "⚠️ 校外赛事全部禁止外出参赛",
        "description": "校园外出活动管控收紧，禁止社团跨区参赛，国赛市赛全部放弃报名，核心参赛价值消失。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bearish", "impact_min": -0.20, "impact_max": -0.09,
        "duration_days": 6,
        "block": "科创",
    },
    {
        "id": "keji_034",
        "title": "🏆 机器人社VEX国赛斩获全能设计大奖",
        "description": "全国VEX精英赛向明战队拿下全能奖！获奖记录可用于高校综评自主招生，社团规模大幅扩张。",
        "stocks_affected": ["robot"],
        "impact_type": "bullish", "impact_min": 0.25, "impact_max": 0.36,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_035",
        "title": "⚠️ 实训车间空调故障高温暂停训练",
        "description": "智能小车车间空调损坏夏季室温超38℃，电子元件极易过热烧毁，仅能早晚短时训练。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bearish", "impact_min": -0.12, "impact_max": -0.07,
        "duration_days": 3,
        "block": "科创",
    },
    {
        "id": "keji_036",
        "title": "🎬 航模社与计算机社合作航拍剪辑程序",
        "description": "航模航拍素材联动计算机社开发自动剪辑小程序，两大社团共享项目经费获区级奖励。",
        "stocks_affected": ["aero-model", "computer"],
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.09,
        "duration_days": 3,
        "block": "科创",
    },
    {
        "id": "keji_037",
        "title": "🏅 OM社指导教师获评全市十佳科创导师",
        "description": "OM带队老师获评全市十佳科创导师，校方将OM设为科创核心标杆社团优先分配资源。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.29,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_038",
        "title": "⚠️ 计算机社高三奥赛主力退出集训",
        "description": "高三核心奥赛队员全力冲刺高考退出编程集训，低年级队员经验不足省赛梯队断层。",
        "stocks_affected": ["computer"],
        "impact_type": "bearish", "impact_min": -0.22, "impact_max": -0.15,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_039",
        "title": "🚀 超科学社自研无代码控制系统推广",
        "description": "社团自研可视化控制程序零基础可调试小车，获教学配套经费，校内曝光度大幅提升。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.20,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_040",
        "title": "⚠️ 航模社校外飞行场地租赁到期",
        "description": "校外合作飞行场地租赁合同到期未续约，户外飞行器调试完全停滞，赛事竞争力大幅削弱。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bearish", "impact_min": -0.17, "impact_max": -0.11,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_041",
        "title": "🤖 机器人社新增3台VEX V5设备",
        "description": "校方专项采购三套全新竞赛机器人套件，硬件储备大幅领先区内各校，可同时多支战队训练。",
        "stocks_affected": ["robot"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.24,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_042",
        "title": "⚠️ OM社道具仓库漏水道具大量损毁",
        "description": "社团道具仓库屋顶漏水，距离市级比赛仅剩一周，大量核心道具报废紧急赶制成本激增。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bearish", "impact_min": -0.13, "impact_max": -0.08,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_043",
        "title": "🎪 五大科创社团联合科创嘉年华",
        "description": "科创板块联合举办校内科创嘉年华，设置竞速飞行体验项目校内售票参与，营收均分。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.16,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_044",
        "title": "💻 计算机社赛事报名系统获多校采购",
        "description": "社团编写赛事线上报名打分系统被多所黄浦中学采购使用，获得软件授权收入扩建实验室。",
        "stocks_affected": ["computer"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.28,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_045",
        "title": "🏆 超科学社区级赛事三连冠",
        "description": "连续三年包揽区级智能小车赛事团体冠军！区教育局点名推广向明训练模式，获专项培育资金。",
        "stocks_affected": ["super-sci"],
        "impact_type": "bullish", "impact_min": 0.22, "impact_max": 0.33,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_046",
        "title": "⚠️ 机器人社内部训练资源分配冲突",
        "description": "两大主力战队争夺实验室时段核心器材矛盾激化，多名骨干社员退社转入OM社。",
        "stocks_affected": ["robot", "om-brain"],
        "impact_type": "mixed", "impact_min": -0.24, "impact_max": 0.08,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_047",
        "title": "🎥 航模社航拍短片入选全市官方宣传片",
        "description": "航模航拍校园风光短片被市教委选用为中小学科创宣传素材全上海校园平台播放。",
        "stocks_affected": ["aero-model"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.22,
        "duration_days": 4,
        "block": "科创",
    },
    {
        "id": "keji_048",
        "title": "⚠️ 线下赛事取消仅保留线上理论笔试",
        "description": "校园安全管控实操类科创赛事全部取消，机器人超科学社核心实操优势无法发挥。",
        "stocks_affected": ["computer"] + ["robot", "super-sci"],
        "impact_type": "mixed", "impact_min": -0.18, "impact_max": 0.10,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_049",
        "title": "🌟 OM社全市美育科创巡回展演",
        "description": "市教育局组织科创美育巡展，OM社为唯一高中创意展演社团巡回全市多所中小学连续三周。",
        "stocks_affected": ["om-brain"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.26,
        "duration_days": 5,
        "block": "科创",
    },
    {
        "id": "keji_050",
        "title": "⚠️ 科创实验楼全面断电检修3天",
        "description": "校园电路整体检修科创实验楼全面断电，编程搭建飞行器调试全部停工，全板块估值同步回调。",
        "stocks_affected": STOCKS_KEJI,
        "impact_type": "bearish", "impact_min": -0.13, "impact_max": -0.06,
        "duration_days": 3,
        "block": "科创",
    },

    # ========== 文艺传媒板块 (wenyi_001 - wenyi_050) ==========
    {
        "id": "wenyi_001",
        "title": "🥁 打击乐社承办全国青少年打击乐展演",
        "description": "全国青少年打击乐大赛落地向明中学，打击乐社作为主场承办社团配套开设音乐学院教授大师班。",
        "stocks_affected": ["percussion"] + STOCKS_WENYI,
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.34,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_002",
        "title": "🎵 蜉蝣天空乐队原创歌曲获最佳作曲奖",
        "description": "蜉蝣天空乐队原创校园民谣参与全市校园音乐大赛拿下高中组最佳原创作曲，校方拨款录制单曲。",
        "stocks_affected": ["mayfly-band", "181-band"],
        "impact_type": "mixed", "impact_min": -0.03, "impact_max": 0.27,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_003",
        "title": "🎬 悬铃影社校园纪实短片获金奖",
        "description": "悬铃影社拍摄校园社团纪实纪录片拿下市级影像赛事金奖，新增专业摄影机灯光器材采购额度。",
        "stocks_affected": ["xuanling", "reporter"],
        "impact_type": "mixed", "impact_min": -0.04, "impact_max": 0.25,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_004",
        "title": "📰 记者社承接全校官方图文采编",
        "description": "学校取消外部宣传外包，全部校内活动采访校刊公众号运营交由记者社全权负责，获稳定运营经费。",
        "stocks_affected": ["reporter"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.22,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_005",
        "title": "🗣️ 沪语社承办全市中学生沪语诵读大赛",
        "description": "黄浦区文旅局选定向明沪语社承办区级沪语诵读赛事，配套开设沪语文化校本拓展课。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.29,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_006",
        "title": "⚠️ 181乐队演出设备故障表演中断",
        "description": "草坪音乐节现场调音台短路181乐队表演中断10分钟，现场观众大量离场，校方缩减演出排期。",
        "stocks_affected": ["181-band", "mayfly-band"],
        "impact_type": "mixed", "impact_min": -0.21, "impact_max": 0.06,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_007",
        "title": "⚠️ 艺术节削减器乐节目名额",
        "description": "艺术节总时长压缩舞台节目总量减半，打击乐社和两支乐队演出机会大幅缩减曝光度下降。",
        "stocks_affected": ["xuanling", "shanghai"] + ["mayfly-band", "181-band", "percussion"],
        "impact_type": "mixed", "impact_min": -0.17, "impact_max": 0.08,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_008",
        "title": "🤝 悬铃影社与记者社联合制作专题栏目",
        "description": "两大传媒社团合作打造校园月度专题栏目，文字采编视频拍摄资源互通共享宣传经费。",
        "stocks_affected": ["xuanling", "reporter"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.12,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_009",
        "title": "⚠️ 打击乐社马林巴琴搬运损坏",
        "description": "社团外出彩排搬运乐器时马林巴琴琴键磕碰损毁无备用乐器，展演曲目被迫删减。",
        "stocks_affected": ["percussion"],
        "impact_type": "bearish", "impact_min": -0.18, "impact_max": -0.12,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_010",
        "title": "🎭 沪语社原创短剧元旦汇演全网播放破十万",
        "description": "沪语社自编自导海派校园短剧作为元旦晚会压轴节目，视频上传校园B站播放量突破十万。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.24,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_011",
        "title": "📺 蜉蝣天空受邀区教育局文艺汇演直播",
        "description": "区级中小学美育汇演邀请蜉蝣天空作为唯一高中乐队登台，全区线上同步直播获跨校曝光。",
        "stocks_affected": ["mayfly-band"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.21,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_012",
        "title": "⚠️ 记者社校刊印刷经费缩减",
        "description": "学校宣传财政收紧校刊印刷预算削减50%，月刊改为双月刊，内容版面减半社员流失。",
        "stocks_affected": ["reporter"],
        "impact_type": "bearish", "impact_min": -0.14, "impact_max": -0.09,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_013",
        "title": "🎸 181乐队原创摇滚单曲校内爆火",
        "description": "181乐队原创摇滚曲目在校内短视频爆火播放量校内第一，学校安排乐队专属草坪专场演出。",
        "stocks_affected": ["181-band", "mayfly-band"],
        "impact_type": "mixed", "impact_min": -0.04, "impact_max": 0.26,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_014",
        "title": "⚠️ 悬铃影社剪辑电脑批量故障",
        "description": "剪辑机房台式机显卡损坏无法渲染视频，市级影像大赛备赛短片剪辑暂停，错失最佳参赛档期。",
        "stocks_affected": ["xuanling"],
        "impact_type": "bearish", "impact_min": -0.19, "impact_max": -0.13,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_015",
        "title": "🏆 打击乐社全国展演斩获团体金奖",
        "description": "全国青少年打击乐展演向明打击乐团斩获高中组团体金奖，校方追加器乐采购经费扩建排练厅。",
        "stocks_affected": ["percussion"] + STOCKS_WENYI,
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.31,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_016",
        "title": "⚠️ 沪语社外聘沪剧教师合同到期",
        "description": "沪语社专职沪剧老师合同到期离校无替代师资，每周方言表演诵读课程全部暂停。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.10,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_017",
        "title": "🎥 记者社开设校园短视频直播频道",
        "description": "记者社新增短视频直播板块校内运动会艺术节全程实时直播，单场观看超两千人次获设备经费。",
        "stocks_affected": ["reporter"],
        "impact_type": "bullish", "impact_min": 0.12, "impact_max": 0.17,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_018",
        "title": "🎵 两支乐队联合校园摇滚专场",
        "description": "蜉蝣天空与181乐队合作举办摇滚音乐节联合售票共享排练场地分摊器材成本，营收均分。",
        "stocks_affected": ["mayfly-band", "181-band"],
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.10,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_019",
        "title": "🤝 悬铃影社与沪语社合作方言微电影",
        "description": "影社拍摄剪辑沪语社提供剧本演员，联合制作海派方言微电影申报市级美育创作项目获批补贴。",
        "stocks_affected": ["xuanling", "shanghai"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.11,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_020",
        "title": "⚠️ 校外文艺演出禁令",
        "description": "外出校园活动管控收紧禁止文艺社团跨区汇演赛事参赛，校外曝光渠道全部关闭。",
        "stocks_affected": ["reporter"] + ["percussion", "mayfly-band", "181-band", "xuanling"],
        "impact_type": "mixed", "impact_min": -0.19, "impact_max": 0.06,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_021",
        "title": "🥁 打击乐社开设全校公益体验课",
        "description": "打击乐社每周开设小军鼓马林巴体验公开课，全校学生免费参与扩招新生30余人。",
        "stocks_affected": ["percussion"],
        "impact_type": "bullish", "impact_min": 0.10, "impact_max": 0.15,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_022",
        "title": "⚠️ 蜉蝣天空主唱高三备考退团",
        "description": "乐队主唱全力备战高考退出社团，无合适替补主唱，多首原创曲目无法登台表演，粉丝关注度下滑。",
        "stocks_affected": ["mayfly-band"],
        "impact_type": "bearish", "impact_min": -0.23, "impact_max": -0.16,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_023",
        "title": "🎬 悬铃影社获区级美育宣传片制作经费",
        "description": "黄浦区教育局委托悬铃影社拍摄全区中小学美育宣传短片，拨付完整制作预算采购专业器材。",
        "stocks_affected": ["xuanling"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.30,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_024",
        "title": "🎤 沪语社校园沪语歌谣大赛200+人参赛",
        "description": "沪语社自主策划校内沪语歌唱大赛设置文创奖品覆盖全校，校方追加海派文化专项扶持经费。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bullish", "impact_min": 0.12, "impact_max": 0.18,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_025",
        "title": "📱 记者社公众号粉丝破四千成校内第一",
        "description": "记者社运营校园官方公众号粉丝突破4000，推文阅读量稳居校内第一，校方加大资源倾斜。",
        "stocks_affected": ["reporter"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.20,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_026",
        "title": "⚠️ 181乐队排练室隔音破损限制排练",
        "description": "乐队排练室隔音层老化破损乐器噪音影响上课，校方规定仅放学后1小时可排练，时长缩减70%。",
        "stocks_affected": ["181-band"],
        "impact_type": "bearish", "impact_min": -0.17, "impact_max": -0.11,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_027",
        "title": "🤝 打击乐社与悬铃影社合作专题纪录片",
        "description": "打击乐团提供演奏素材悬铃影社拍摄制作专题纪录片，校内多媒体教室循环展播，共享宣传流量。",
        "stocks_affected": ["percussion", "xuanling"],
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.09,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_028",
        "title": "⚠️ 音乐大赛取消乐队组别",
        "description": "市级音乐赛事调整删除摇滚校园乐队参赛通道，两支乐队失去市级赛事曝光渠道。",
        "stocks_affected": ["percussion"] + ["mayfly-band", "181-band"],
        "impact_type": "mixed", "impact_min": -0.13, "impact_max": 0.05,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_029",
        "title": "📖 沪语社原创诗集全校刊印分发",
        "description": "沪语社社员原创方言诗歌汇编成册校方印刷分发全年级，获文创出版补贴。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.22,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_030",
        "title": "🤝 记者社与沪语社合作方言文化专栏",
        "description": "记者社公众号开设沪语文化固定专栏由沪语社供稿，每周更新方言故事诵读稿件联动涨粉。",
        "stocks_affected": ["reporter", "shanghai"],
        "impact_type": "bullish", "impact_min": 0.05, "impact_max": 0.08,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_031",
        "title": "🎵 打击乐社全面升级乐器储备",
        "description": "校方拨付美育专项经费采购四台全新马林巴大型定音鼓，可编排高难度合奏曲目。",
        "stocks_affected": ["percussion"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.27,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_032",
        "title": "⚠️ 蜉蝣天空录音设备进水损毁",
        "description": "排练室水管渗漏录音声卡麦克风泡水报废，原创单曲发布延期流量热度流失。",
        "stocks_affected": ["mayfly-band"],
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.10,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_033",
        "title": "🎬 悬铃影社校园微电影展映周",
        "description": "悬铃影社自主举办为期一周的校园影像展展出历年获奖短片，外校影视社团到校交流学习。",
        "stocks_affected": ["xuanling"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.23,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_034",
        "title": "🎂 181乐队为校庆创作主题曲",
        "description": "学校校庆邀约181乐队创作原创主题曲作为开场曲目演出，获得校庆专项经费全校循环播放。",
        "stocks_affected": ["181-band"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.29,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_035",
        "title": "⚠️ 沪语社校内沙龙参与人数低迷",
        "description": "每周沪语诵读沙龙参与学生不足十人活动产出稀少，校方缩减社团活动经费。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bearish", "impact_min": -0.12, "impact_max": -0.07,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_036",
        "title": "🏆 记者社校刊入围市级十佳校园刊物",
        "description": "全市校园刊物评比记者社主办校刊入围十佳，印刷采编经费翻倍规模扩张。",
        "stocks_affected": ["reporter"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.25,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_037",
        "title": "🎪 五大文娱社团联合承办艺术节",
        "description": "打击乐两支乐队悬铃影社沪语社联合承办艺术节全部文艺舞台节目，共享门票文创营收。",
        "stocks_affected": STOCKS_WENYI,
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.18,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_038",
        "title": "⚠️ 悬铃影社存储硬盘不足",
        "description": "剪辑机房存储硬盘容量不足拍摄短片素材需频繁删除，大型纪录片无法完整存储制作。",
        "stocks_affected": ["xuanling"],
        "impact_type": "bearish", "impact_min": -0.15, "impact_max": -0.09,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_039",
        "title": "🏆 打击乐社国风改编获创意专项奖",
        "description": "全国打击乐展演中向明乐团自主改编国风打击乐曲目拿下全场唯一创意专项奖。",
        "stocks_affected": ["percussion"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.21,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_040",
        "title": "⚠️ 两支乐队排练室时段冲突",
        "description": "校内仅一间专业乐队排练室，蜉蝣天空与181乐队训练时段重叠双方缩减训练时长。",
        "stocks_affected": ["mayfly-band", "181-band"],
        "impact_type": "bearish", "impact_min": -0.07, "impact_max": -0.04,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_041",
        "title": "📖 沪语社与记者社联名文化特刊",
        "description": "记者社排版印刷沪语社供稿方言故事诵读文稿联合推出校园文化特刊，纳入校本读物。",
        "stocks_affected": ["shanghai", "reporter"],
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.10,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_042",
        "title": "⚠️ 全校美育经费削减25%",
        "description": "学校年度财政收紧文娱板块统一缩减采购演出经费，舞台节目器材采购全部缩水。",
        "stocks_affected": STOCKS_WENYI,
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.06,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_043",
        "title": "🎥 悬铃影社三件作品入选全市展映片单",
        "description": "市教育局遴选悬铃影社三部原创短片纳入全市中小学影像展映片单，全市各校组织集体观看。",
        "stocks_affected": ["xuanling"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.28,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_044",
        "title": "⚠️ 记者社摄影骨干高三离校",
        "description": "高三摄影主力队员全力备战高考退出社团，校刊短视频产出缩减公众号更新频次放缓。",
        "stocks_affected": ["reporter"],
        "impact_type": "bearish", "impact_min": -0.18, "impact_max": -0.12,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_045",
        "title": "🎵 蜉蝣天空专场门票一小时售罄",
        "description": "蜉蝣天空乐队原创专场音乐会门票上线一小时售空加开第二场，营收翻倍补充录音器材。",
        "stocks_affected": ["mayfly-band"],
        "impact_type": "bullish", "impact_min": 0.22, "impact_max": 0.32,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_046",
        "title": "⚠️ 打击乐社排练厅空调故障高温",
        "description": "夏季排练厅空调损坏室温过高马林巴琴琴键热胀变形，仅能短时分声部练习合奏停滞。",
        "stocks_affected": ["percussion"],
        "impact_type": "bearish", "impact_min": -0.14, "impact_max": -0.09,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_047",
        "title": "📻 181乐队单曲登区级校园音乐电台",
        "description": "区级校园广播电台固定播放181乐队校庆主题曲覆盖黄浦全部初高中，跨校知名度大幅提升。",
        "stocks_affected": ["181-band"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.23,
        "duration_days": 4,
        "block": "文艺",
    },
    {
        "id": "wenyi_048",
        "title": "🎭 沪语社承办全市中学生沪语戏剧节",
        "description": "区级沪语戏剧节落地向明，沪语社三部原创方言短剧入选市级展演剧目获文旅局专项经费。",
        "stocks_affected": ["shanghai"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.27,
        "duration_days": 5,
        "block": "文艺",
    },
    {
        "id": "wenyi_049",
        "title": "🎬 悬铃影社与乐队合作摇滚MV全网传播",
        "description": "影社拍摄剪辑蜉蝣天空181提供演唱演奏素材联合制作校园摇滚MV，三大社团共享流量。",
        "stocks_affected": ["xuanling", "mayfly-band", "181-band"],
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.09,
        "duration_days": 3,
        "block": "文艺",
    },
    {
        "id": "wenyi_050",
        "title": "⚠️ 大礼堂封闭翻新所有舞台取消",
        "description": "校内大礼堂翻新施工封闭艺术节乐队专场打击乐展演全部延后两月，短期无舞台曝光。",
        "stocks_affected": ["reporter", "xuanling"] + ["percussion", "mayfly-band", "181-band"],
        "impact_type": "mixed", "impact_min": -0.14, "impact_max": 0.06,
        "duration_days": 5,
        "block": "文艺",
    },

    # ========== 思辨学术板块 (sibian_001 - sibian_030) ==========
    {
        "id": "sibian_001",
        "title": "🏛️ 模联社承办黄浦区模联大会",
        "description": "黄浦区教育局选定向明模联社主办区级模联会议，二十所中学参会拨付场地会务专项经费。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "mixed", "impact_min": -0.04, "impact_max": 0.33,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_002",
        "title": "🏆 辩论社拿下全市华语辩论团体冠军",
        "description": "市级高中生辩论赛决赛向明辩论社击败多所市重点拿下年度团体冠军，校方拨付专项经费。",
        "stocks_affected": ["debate", "mun"],
        "impact_type": "mixed", "impact_min": -0.03, "impact_max": 0.29,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_003",
        "title": "⚠️ 市级模联议题冷门备赛热情低迷",
        "description": "本年度市级模联议题为冷门历史议题，社员调研资料稀缺参与热情大幅下降，招新预期下滑。",
        "stocks_affected": ["mun"],
        "impact_type": "bearish", "impact_min": -0.17, "impact_max": -0.11,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_004",
        "title": "⚠️ 辩论社核心一辩四辩高三退社",
        "description": "辩论社两名核心主力全力备战高考退出社团，低年级队员赛场经验不足，区级备赛实力下滑。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.21, "impact_max": -0.14,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_005",
        "title": "🌍 模联社获全国模联总决赛直通名额",
        "description": "向明模联社区级大会承办成绩优异获全国模联总决赛专属直通名额，全市仅两所高中拥有。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.28,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_006",
        "title": "⚠️ 市级辩论赛压缩参赛名额",
        "description": "市级辩论联赛压缩参赛队伍各校仅一支代表队参赛，辩论社无法分梯队练兵低年级缺实战机会。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.13, "impact_max": -0.08,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_007",
        "title": "🤝 模联与辩论社联合校园思辨沙龙",
        "description": "两大学术社团合作开设午间思辨沙龙模联国际议题辩论社会时事辩题同步研讨，共享资源。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.11,
        "duration_days": 3,
        "block": "思辨",
    },
    {
        "id": "sibian_008",
        "title": "⚠️ 模联社英文指导教师调离",
        "description": "模联社金牌英文指导老师工作调动无替代教师，英文模联备赛停滞只能参与中文会场。",
        "stocks_affected": ["mun"],
        "impact_type": "bearish", "impact_min": -0.19, "impact_max": -0.13,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_009",
        "title": "🗣️ 辩论社开设全校辩论入门公开课",
        "description": "辩论社每周开设免费辩论逻辑攻防技巧公开课吸引大量新生加入，社团规模扩充50%。",
        "stocks_affected": ["debate"],
        "impact_type": "bullish", "impact_min": 0.11, "impact_max": 0.16,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_010",
        "title": "⚠️ 全国模联禁止跨市外出参会",
        "description": "校园外出活动管控取消全国市级跨区模联外出参会资格，仅能校内区级小规模会议。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "mixed", "impact_min": -0.24, "impact_max": 0.05,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_011",
        "title": "🏆 模联社全国总决赛最佳代表团双奖",
        "description": "全国模联总决赛向明代表团拿下最佳代表团团体奖，多名社员获个人单项奖高校综评加分。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.25, "impact_max": 0.36,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_012",
        "title": "⚠️ 辩论社校内思辨杯报名连续两年下滑",
        "description": "校内年度辩论赛新生报名人数逐年减少赛事场次奖项同步压缩，校方缩减赛事经费。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.12, "impact_max": -0.07,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_013",
        "title": "🏛️ 模联社新增独立模联会议室配全套设备",
        "description": "校方划拨人文专项经费打造专属模联议事会议室配齐全套标准化会务硬件。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.23,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_014",
        "title": "⚠️ 综评加分规则调整辩论加分超模联",
        "description": "市教委调整人文赛事综评加分规则辩论赛获奖加分高于模联赛事，辩论社规模扩张。",
        "stocks_affected": ["debate", "mun"],
        "impact_type": "mixed", "impact_min": -0.05, "impact_max": 0.20,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_015",
        "title": "📖 模联社调研手册被区教育局全区印发",
        "description": "模联社编写国际议题调研工具书，黄浦区教育局统一印刷发放给全区中学模联社团。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.21,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_016",
        "title": "⚠️ 辩论社多媒体设备全部老化",
        "description": "辩论训练教室投影仪录音录像设备老化损坏，赛场复盘技巧演示训练停滞，夺冠预期下调。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.15, "impact_max": -0.09,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_017",
        "title": "🎪 模联与辩论社联合校园时政思辨节",
        "description": "两大学术社团合作举办全校时政思辨节同步开设模拟联合国会场华语辩论擂台，均分会务经费。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.10,
        "duration_days": 3,
        "block": "思辨",
    },
    {
        "id": "sibian_018",
        "title": "🌍 模联议题聚焦热门气候治理",
        "description": "市级模联议题为全球气候治理热点议题，网络调研素材丰富社员主动扩充备赛时长报名激增。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.10, "impact_max": 0.14,
        "duration_days": 3,
        "block": "思辨",
    },
    {
        "id": "sibian_019",
        "title": "⚠️ 辩论社外聘专业教练合同到期离校",
        "description": "校外专业辩论教练合同到期未续约，高阶战术质询技巧训练课程全部取消，仅能开展基础训练。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.18, "impact_max": -0.12,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_020",
        "title": "⚠️ 人文类社团经费统一缩减30%",
        "description": "学校财政收紧思辨学术板块经费削减三成，会议奖品打印场地配套预算减半。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "bearish", "impact_min": -0.14, "impact_max": -0.08,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_021",
        "title": "🏫 模联社与高校国关学院达成共建",
        "description": "大中贯通人文合作落地高校国关专业导师每月入校，开展模联外交文书专项讲座。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.27,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_022",
        "title": "⚠️ 辩论社市级初赛发挥失常止步小组赛",
        "description": "区级辩论赛初赛队员攻防失误频繁总分不足淘汰，连续两年未晋级市级复赛，士气低迷。",
        "stocks_affected": ["debate"],
        "impact_type": "bearish", "impact_min": -0.26, "impact_max": -0.18,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_023",
        "title": "🌐 模联社承办全国模联上海分区线上会场",
        "description": "全国模联线上分会场选定向明模联社主办，线上会务议题主持全权交由社团负责覆盖全国百所中学。",
        "stocks_affected": ["mun"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.24,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_024",
        "title": "📖 辩论社原创辩题库获多所中学采购",
        "description": "辩论社整理全套初高中时事辩题库黄浦多所中学采购用于校内赛事训练，社团获得版权收入。",
        "stocks_affected": ["debate"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.22,
        "duration_days": 4,
        "block": "思辨",
    },
    {
        "id": "sibian_025",
        "title": "⚠️ 模联会议室临时征用月度议事延期",
        "description": "模联专属会议室临时被校庆活动征用，月度校内模拟会议延期社员实战训练中断。",
        "stocks_affected": ["mun"],
        "impact_type": "bearish", "impact_min": -0.11, "impact_max": -0.07,
        "duration_days": 3,
        "block": "思辨",
    },
    {
        "id": "sibian_026",
        "title": "🤝 模联与辩论社联合英文思辨课程",
        "description": "两大社团整合师资开设英文思辨课同步训练英文辩论逻辑模联立场文件写作，共享外教资源。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.09,
        "duration_days": 3,
        "block": "思辨",
    },
    {
        "id": "sibian_027",
        "title": "⚠️ 全国模联取消线下改为云端会议",
        "description": "外出管控收紧全国模联全部改为线上云端会场，线下外交谈判会场流程训练无法开展。",
        "stocks_affected": ["debate"] + ["mun"],
        "impact_type": "mixed", "impact_min": -0.18, "impact_max": 0.08,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_028",
        "title": "🏆 辩论社校内思辨杯增设综评加分奖",
        "description": "校内辩论赛设置专属综评实践奖项获奖记录可用于高校自主招生，新生报名人数暴涨三倍。",
        "stocks_affected": ["debate"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.31,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_029",
        "title": "⚠️ 模联社英文文书骨干高三离校",
        "description": "高三英文主力队员备战高考退社，低年级社员英文写作水平不足，全国模联赛事文书质量下滑。",
        "stocks_affected": ["mun"],
        "impact_type": "bearish", "impact_min": -0.20, "impact_max": -0.14,
        "duration_days": 5,
        "block": "思辨",
    },
    {
        "id": "sibian_030",
        "title": "🎓 两大思辨社团联合暑期时政研学营",
        "description": "模联辩论社合作开设暑期时政研学营，设置议题调研模拟议事辩论擂台综合课程全区报名。",
        "stocks_affected": ["mun", "debate"],
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.12,
        "duration_days": 4,
        "block": "思辨",
    },

    # ========== 校园体育板块 (tiyu_001 - tiyu_040) ==========
    {
        "id": "tiyu_001",
        "title": "🏆 篮球社全国U18三人篮球女子组冠军",
        "description": "全国U18三人篮球锦标赛向明女篮登顶全国总冠军！上海高中篮球标杆社团，校方采购全套专业装备。",
        "stocks_affected": ["basketball"] + STOCKS_TIYU,
        "impact_type": "bullish", "impact_min": 0.06, "impact_max": 0.38,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_002",
        "title": "🏆 冰壶社市陆地冰壶锦标赛包揽金银双奖",
        "description": "市级陆地冰壶赛事向明冰壶社两支代表队分获冠亚军，成为上海高中冰壶特色社团。",
        "stocks_affected": ["curling"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.30,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_003",
        "title": "⚠️ 足球场翻新封闭4个月训练暂停",
        "description": "足球场草坪翻新工程开工全时段封闭，无场地开展对抗训练班级联赛，区级备赛进度大幅滞后。",
        "stocks_affected": ["basketball", "badminton", "curling"] + ["football"],
        "impact_type": "mixed", "impact_min": -0.22, "impact_max": 0.06,
        "duration_days": 6,
        "block": "体育",
    },
    {
        "id": "tiyu_004",
        "title": "🏸 羽毛球社承办黄浦区联赛主场",
        "description": "黄浦区选定向明羽毛球社主办区级羽毛球联赛，校内体育馆改造专业赛场获得赛事承办经费。",
        "stocks_affected": ["badminton"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.26,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_005",
        "title": "⚠️ 篮球社主力前锋脚踝重伤赛季报销",
        "description": "篮球社核心得分前锋训练扭伤脚踝至少三个月无法参训，球队进攻战力大幅下滑夺冠预期下调。",
        "stocks_affected": ["basketball"],
        "impact_type": "bearish", "impact_min": -0.19, "impact_max": -0.13,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_006",
        "title": "⚠️ 体育专项经费缩减28%",
        "description": "学校财政收紧体育板块经费统一压缩，场地维护球具采购外出参赛差旅全部缩水。",
        "stocks_affected": STOCKS_TIYU,
        "impact_type": "bearish", "impact_min": -0.18, "impact_max": -0.07,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_007",
        "title": "⚽ 足球社承办校内向明杯班级联赛",
        "description": "足球社自主策划全校班级足球联赛二十余班级组队参赛，设置冠亚季军奖杯全校师生观赛参与。",
        "stocks_affected": ["football"],
        "impact_type": "bullish", "impact_min": 0.12, "impact_max": 0.17,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_008",
        "title": "⚠️ 冰壶社专职教练调任他校",
        "description": "冰壶社唯一专业指导教师工作调动无替代教练，战术投壶技巧专项训练暂停，市级赛事预期下调。",
        "stocks_affected": ["curling"],
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.10,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_009",
        "title": "🏸 羽毛球社区级联赛包揽男女单打冠军",
        "description": "黄浦区羽毛球联赛向明羽毛球社包揽男女单打冠军获市级总决赛专属参赛名额。",
        "stocks_affected": ["badminton"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.23,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_010",
        "title": "🎪 四大体育社团联合体育嘉年华",
        "description": "篮球足球羽毛球冰壶社联合举办校园体育嘉年华，设置各类体验项目校内售票参与营收均分。",
        "stocks_affected": STOCKS_TIYU,
        "impact_type": "bullish", "impact_min": 0.08, "impact_max": 0.20,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_011",
        "title": "🏀 篮球社新增两片室内标准半场",
        "description": "校方拨付体教融合专项经费扩建两片室内篮球训练半场，配套专业计分牌防滑塑胶地面。",
        "stocks_affected": ["basketball"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.29,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_012",
        "title": "⚠️ 足球社器材被盗训练停摆",
        "description": "足球社存放器材仓库门锁损坏大批量足球护腿板训练背心被盗，仅能开展无对抗体能训练。",
        "stocks_affected": ["football"],
        "impact_type": "bearish", "impact_min": -0.14, "impact_max": -0.09,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_013",
        "title": "🥌 冰壶社新建六条标准陆地冰壶赛道",
        "description": "区级冰雪运动扶持资金落地向明，校内体育馆改造六条陆地冰壶标准赛道，扩招梯队员。",
        "stocks_affected": ["curling"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.25,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_014",
        "title": "⚠️ 羽毛球馆照明老化限时开放",
        "description": "羽毛球馆照明灯具老化频闪，校方规定仅白天开放训练，晚间高强度对抗训练取消时长减半。",
        "stocks_affected": ["badminton"],
        "impact_type": "bearish", "impact_min": -0.13, "impact_max": -0.08,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_015",
        "title": "🏀 篮球社受邀全国C8联盟邀请赛",
        "description": "全国中学篮球联盟邀请赛邀请向明篮球社作为上海代表参赛，全国线上直播获跨市曝光。",
        "stocks_affected": ["basketball"],
        "impact_type": "bullish", "impact_min": 0.22, "impact_max": 0.32,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_016",
        "title": "⚠️ 校外体育赛事全部禁止外出",
        "description": "校园外出活动管控收紧禁止体育社团跨市参加市级全国赛事，高端赛事曝光渠道关闭。",
        "stocks_affected": STOCKS_TIYU,
        "impact_type": "bearish", "impact_min": -0.21, "impact_max": -0.09,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_017",
        "title": "⚽ 足球社与职业青训俱乐部达成共建",
        "description": "大中体教融合落地本地职业足球青训教练固定入校，负责战术体能专项训练。",
        "stocks_affected": ["football"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.21,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_018",
        "title": "⚠️ 冰壶社锦标赛决赛失误错失冠军",
        "description": "区级冰壶锦标赛决赛最后一投力度失误总分落后，连续两年无缘冠军，社员士气低迷。",
        "stocks_affected": ["curling"],
        "impact_type": "bearish", "impact_min": -0.23, "impact_max": -0.16,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_019",
        "title": "🏸 羽毛球社校内羽明杯双打公开赛",
        "description": "羽毛球社自主策划校内双打公开赛设置专业球拍奖品，吸引全校百余名学生参赛。",
        "stocks_affected": ["badminton"],
        "impact_type": "bullish", "impact_min": 0.13, "impact_max": 0.18,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_020",
        "title": "⚠️ 篮球校内联赛裁判短缺多场赛程延期",
        "description": "校内篮球联赛学生裁判报名人数不足多场班级对战被迫延期，赛事连贯性断裂热度下降。",
        "stocks_affected": ["basketball"],
        "impact_type": "bearish", "impact_min": -0.10, "impact_max": -0.06,
        "duration_days": 3,
        "block": "体育",
    },
    {
        "id": "tiyu_021",
        "title": "🎪 四大体育社团联合公益体验周",
        "description": "篮球足球羽毛球冰壶社合作开展一周公益体验活动每日开放不同运动项目试训扩招新人。",
        "stocks_affected": STOCKS_TIYU,
        "impact_type": "bullish", "impact_min": 0.07, "impact_max": 0.16,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_022",
        "title": "⚠️ 足球社核心中场转学离校",
        "description": "足球社主力中场转学球队攻防转换核心缺失，区级联赛战术体系需重新调整备赛周期拉长。",
        "stocks_affected": ["football"],
        "impact_type": "bearish", "impact_min": -0.17, "impact_max": -0.11,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_023",
        "title": "📖 冰壶社校本教材被区教育局全区印发",
        "description": "冰壶社编写陆地冰壶基础训练校本教材，黄浦区教育局统一印刷分发全区冰雪运动课程使用。",
        "stocks_affected": ["curling"],
        "impact_type": "bullish", "impact_min": 0.15, "impact_max": 0.22,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_024",
        "title": "⚠️ 羽毛球社外出联赛大巴故障迟到判负",
        "description": "赴区级羽毛球联赛校车半路故障全队迟到超过开赛时间，单打项目全部判负淘汰。",
        "stocks_affected": ["badminton"],
        "impact_type": "bearish", "impact_min": -0.20, "impact_max": -0.14,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_025",
        "title": "🏀 女篮冠军纪录片循环展播新生激增",
        "description": "学校拍摄女篮全国冠军纪实短片校内多媒体循环播放，大量女生报名篮球社女篮梯队。",
        "stocks_affected": ["basketball"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.24,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_026",
        "title": "⚠️ 体育馆空调检修限时缩减训练",
        "description": "体育馆中央空调检修封闭夏季室内高温，篮球羽毛球冰壶仅能早晚短时训练。",
        "stocks_affected": ["football"] + ["basketball", "badminton", "curling"],
        "impact_type": "mixed", "impact_min": -0.12, "impact_max": 0.05,
        "duration_days": 3,
        "block": "体育",
    },
    {
        "id": "tiyu_027",
        "title": "⚽ 足球社新增人工草皮备用训练场",
        "description": "校方铺设小型人工草皮备用场地，雨天原有球场维修时可正常开展足球对抗训练。",
        "stocks_affected": ["football"],
        "impact_type": "bullish", "impact_min": 0.12, "impact_max": 0.19,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_028",
        "title": "⚠️ 冰壶社石头磨损无经费更换",
        "description": "陆地冰壶石头底部防滑层磨损投壶轨迹不稳定，器材更新经费暂缓审批训练体验感下滑。",
        "stocks_affected": ["curling"],
        "impact_type": "bearish", "impact_min": -0.12, "impact_max": -0.07,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_029",
        "title": "🏸 羽毛球社与市队达成共建基地",
        "description": "市羽毛球队与向明羽毛球社共建青少年训练基地，专业运动员入校指导高阶技巧。",
        "stocks_affected": ["badminton"],
        "impact_type": "bullish", "impact_min": 0.18, "impact_max": 0.27,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_030",
        "title": "⚠️ 篮球社足球社共用的更衣室储物不足",
        "description": "室外看台更衣室储物柜数量不足两大社团共用储物柜，球鞋护具丢失情况频发训练装备损耗。",
        "stocks_affected": ["basketball", "football"],
        "impact_type": "bearish", "impact_min": -0.08, "impact_max": -0.05,
        "duration_days": 3,
        "block": "体育",
    },
    {
        "id": "tiyu_031",
        "title": "🥌 冰壶社承办全市中小学公开赛",
        "description": "上海市中小学冰雪运动公开赛选定向明冰壶社为主办方，三十余所中学组队参赛获全市曝光。",
        "stocks_affected": ["curling"],
        "impact_type": "bullish", "impact_min": 0.20, "impact_max": 0.31,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_032",
        "title": "⚠️ 足球社区联赛主力集体感冒缺赛",
        "description": "区级足球联赛赛前多名主力队员流感发烧无法参赛，替补队员实力不足小组赛淘汰。",
        "stocks_affected": ["football"],
        "impact_type": "bearish", "impact_min": -0.24, "impact_max": -0.17,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_033",
        "title": "🏀 篮球社开设3v3篮球公益课",
        "description": "篮球社每周开设3v3入门公益训练课不分男女零基础招生扩招新生四十余人。",
        "stocks_affected": ["basketball"],
        "impact_type": "bullish", "impact_min": 0.10, "impact_max": 0.15,
        "duration_days": 3,
        "block": "体育",
    },
    {
        "id": "tiyu_034",
        "title": "⚠️ 羽毛球场地塑胶起泡禁止高速对抗",
        "description": "羽毛球场地塑胶老化起泡校方限制高速单打对抗仅允许慢速双打基础挥拍，单打备赛停滞。",
        "stocks_affected": ["badminton"],
        "impact_type": "bearish", "impact_min": -0.16, "impact_max": -0.10,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_035",
        "title": "⚽ 足球社新风杯校内赛改制32队",
        "description": "校内新风杯改制扩军至32支班级队伍，赛事规模翻倍校园足球热度全面引爆。",
        "stocks_affected": ["football"],
        "impact_type": "bullish", "impact_min": 0.14, "impact_max": 0.20,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_036",
        "title": "⚠️ 冰壶社核心队员受伤缺赛3个月",
        "description": "冰壶社主力投壶手训练中手腕扭伤需停训休养，市级锦标赛核心阵容残缺。",
        "stocks_affected": ["curling"],
        "impact_type": "bearish", "impact_min": -0.18, "impact_max": -0.12,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_037",
        "title": "🏸 羽毛球社新增4片专业羽毛球场地",
        "description": "校方利用闲置空间改造成标准羽毛球馆扩至8片场地，训练时长翻倍市级夺冠预期拉满。",
        "stocks_affected": ["badminton"],
        "impact_type": "bullish", "impact_min": 0.22, "impact_max": 0.30,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_038",
        "title": "⚠️ 篮球社高三主力队员集体退队",
        "description": "高三篮球主力全力备战高考全部退出球队训练，低年级梯队尚未成熟，新风杯战力断崖下滑。",
        "stocks_affected": ["basketball"],
        "impact_type": "bearish", "impact_min": -0.21, "impact_max": -0.15,
        "duration_days": 5,
        "block": "体育",
    },
    {
        "id": "tiyu_039",
        "title": "🥌 冰壶社增设冰雪运动专项奖学金",
        "description": "学校设立冰雪运动专项奖学金激励冰壶社优秀队员，训练积极性大幅提升社团实力增强。",
        "stocks_affected": ["curling"],
        "impact_type": "bullish", "impact_min": 0.16, "impact_max": 0.22,
        "duration_days": 4,
        "block": "体育",
    },
    {
        "id": "tiyu_040",
        "title": "⚠️ 罕见暴雨致体育馆屋顶渗漏",
        "description": "连续暴雨体育馆屋顶渗漏，篮球羽毛球冰壶室内训练被迫暂停一周，赛事备赛进度受损。",
        "stocks_affected": ["basketball", "badminton", "curling"],
        "impact_type": "bearish", "impact_min": -0.10, "impact_max": -0.05,
        "duration_days": 3,
        "block": "体育",
    },
]


# ============================================================
# 第三部分：因果关系事件链 (CAUSE_CHAINS)
# ============================================================
# 起因事件触发后，1-3天后必定触发对应的经过事件
# chain_id 用于关联起因和经过
# ============================================================

CAUSE_CHAINS = [
    {
        "id": "chain_001",
        "title_cause": "📰 爆料：有匿名帖称某社团存在经费滥用",
        "desc_cause": "校园论坛出现匿名帖子，直指某热门社团存在活动经费报销不规范的情况，全校师生热议。校方发表声明将严肃调查。",
        "stocks_affected_cause": STOCKS_KEJI + STOCKS_WENYI,
        "impact_cause": "mixed", "impact_min_cause": -0.06, "impact_max_cause": -0.02,
        "duration_cause": 1,
        "title_process": "📋 经费审查结果公布：涉事社团整改",
        "desc_process": "校方完成经费审查，确认部分社团存在报销流程不规范问题，要求限期整改。被点名的社团声誉受损，社费冻结。",
        "stocks_affected_process": STOCKS_KEJI + STOCKS_WENYI,
        "impact_process": "mixed", "impact_min_process": -0.12, "impact_max_process": 0.05,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_002",
        "title_cause": "⚡ 传闻：某大型科创企业有意赞助向明",
        "desc_cause": "据传某知名科技企业计划与向明中学达成校企合作，将赞助科创社团设备并开设联合实验室。市场反应积极但消息未确认。",
        "stocks_affected_cause": STOCKS_KEJI,
        "impact_cause": "bullish", "impact_min_cause": 0.05, "impact_max_cause": 0.10,
        "duration_cause": 1,
        "title_process": "✅ 校企合作正式签约！赞助设备到位",
        "desc_process": "传言成真！科技企业与向明正式签约，赞助总额超50万元的全新科创设备，并为优秀社员提供暑期实习机会。",
        "stocks_affected_process": STOCKS_KEJI,
        "impact_process": "bullish", "impact_min_process": 0.15, "impact_max_process": 0.25,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_003",
        "title_cause": "📢 教育局或将出台社团限制新政",
        "desc_cause": "据内部人士透露，教育局正考虑出台新规，限制高中社团每周活动时长不得超过2课时。社团圈一片哗然。",
        "stocks_affected_cause": ALL_STOCKS,
        "impact_cause": "bearish", "impact_min_cause": -0.05, "impact_max_cause": -0.01,
        "duration_cause": 1,
        "title_process": "📜 新政落地：社团活动限制正式实施",
        "desc_process": "教育局正式下发文件，高中社团每周活动限2课时，取消周末实验室开放和晚间实训。全板块受冲击。",
        "stocks_affected_process": ALL_STOCKS,
        "impact_process": "bearish", "impact_min_process": -0.15, "impact_max_process": -0.05,
        "duration_process": 6,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_004",
        "title_cause": "🎬 悬铃影社宣布筹拍大型校园纪录片",
        "desc_cause": "悬铃影社在社团大会上宣布将拍摄一部反映向明三年校园生活的大型纪录片，计划招募全校演员。项目前景乐观。",
        "stocks_affected_cause": ["xuanling"],
        "impact_cause": "bullish", "impact_min_cause": 0.05, "impact_max_cause": 0.08,
        "duration_cause": 1,
        "title_process": "🎥 纪录片杀青！首映式全校瞩目",
        "desc_process": "历时多日拍摄，纪录片《向明时光》正式杀青并在学校礼堂举行首映式。全场座无虚席，校领导高度评价。",
        "stocks_affected_process": ["xuanling", "reporter"],
        "impact_process": "bullish", "impact_min_process": 0.12, "impact_max_process": 0.20,
        "duration_process": 5,
        "delay_min": 2, "delay_max": 3,
    },
    {
        "id": "chain_005",
        "title_cause": "🔥 两个乐队在社交媒体上发生口角",
        "desc_cause": "蜉蝣天空与181乐队成员在社交平台上因演出档期分配问题公开争论，校园舆论分裂为两派，两社团关系紧张。",
        "stocks_affected_cause": ["mayfly-band", "181-band"],
        "impact_cause": "bearish", "impact_min_cause": -0.08, "impact_max_cause": -0.03,
        "duration_cause": 1,
        "title_process": "🤝 两大乐队握手言和宣布联合巡演",
        "desc_process": "在学校老师调解下，两支乐队队长公开发表联合声明，宣布将举办联合校园巡演。粉丝群体欢呼雀跃！",
        "stocks_affected_process": ["mayfly-band", "181-band", "percussion"],
        "impact_process": "bullish", "impact_min_process": 0.10, "impact_max_process": 0.18,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_006",
        "title_cause": "🏀 篮球社核心与教练发生训练理念冲突",
        "desc_cause": "篮球社主力队员与教练在战术安排上产生严重分歧，多名队员拒绝参加集训，球队内部气氛紧张。",
        "stocks_affected_cause": ["basketball"],
        "impact_cause": "bearish", "impact_min_cause": -0.10, "impact_max_cause": -0.05,
        "duration_cause": 1,
        "title_process": "💪 危机化解！球队新战术大获成功",
        "desc_process": "经多方调解，教练和球员达成共识启用新战术体系。在随后的友谊赛中球队打出酣畅淋漓的大胜！",
        "stocks_affected_process": ["basketball"],
        "impact_process": "bullish", "impact_min_process": 0.15, "impact_max_process": 0.22,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_007",
        "title_cause": "🔬 超科学社发现核心技术存在重大缺陷",
        "desc_cause": "超科学社在赛前测试中发现智能小车避障算法存在严重漏洞，在复杂路况下频繁误判。市级比赛在即！",
        "stocks_affected_cause": ["super-sci"],
        "impact_cause": "bearish", "impact_min_cause": -0.12, "impact_max_cause": -0.06,
        "duration_cause": 1,
        "title_process": "🚀 算法突破！小车通过极限测试",
        "desc_process": "联合计算机社日夜攻关，重写了核心避障算法。在新一轮测试中小车完美通过所有障碍，性能大幅提升！",
        "stocks_affected_process": ["super-sci", "computer"],
        "impact_process": "bullish", "impact_min_process": 0.18, "impact_max_process": 0.28,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 2,
    },
    {
        "id": "chain_008",
        "title_cause": "📉 模联议题设置遭外界批评",
        "desc_cause": "模联社即将举办的会议议题被校外人士批评为「脱离学生实际过于空泛」，社内对议题方向产生严重分歧。",
        "stocks_affected_cause": ["mun"],
        "impact_cause": "bearish", "impact_min_cause": -0.08, "impact_max_cause": -0.04,
        "duration_cause": 1,
        "title_process": "🌟 议题改革获赞誉参会人数创新高",
        "desc_process": "模联社紧急调整议题方向，聚焦校园和青少年发展话题。新议题获得广泛好评，报名参会学校数量创新高！",
        "stocks_affected_process": ["mun"],
        "impact_process": "bullish", "impact_min_process": 0.15, "impact_max_process": 0.24,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_009",
        "title_cause": "⚽ 足球社被匿名举报违规使用训练经费",
        "desc_cause": "有人向校方匿名举报足球社存在训练经费虚报情况，校纪委宣布介入调查。社团训练暂停，队内人心惶惶。",
        "stocks_affected_cause": ["football"],
        "impact_cause": "bearish", "impact_min_cause": -0.14, "impact_max_cause": -0.08,
        "duration_cause": 1,
        "title_process": "✅ 调查结束！足球社证实清白恢复训练",
        "desc_process": "校纪委完成调查，足球社经费使用规范无违规行为。反倒是举报被证实为竞争对手恶意中伤。球队士气反弹！",
        "stocks_affected_process": ["football"],
        "impact_process": "bullish", "impact_min_process": 0.12, "impact_max_process": 0.18,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_010",
        "title_cause": "🏗️ 学校宣布将新建综合活动中心",
        "desc_cause": "校长在周一升旗仪式上宣布，学校已获批新建一座综合活动中心，包含室内球场、演出厅和科创实验室。方案待定。",
        "stocks_affected_cause": ALL_STOCKS,
        "impact_cause": "bullish", "impact_min_cause": 0.03, "impact_max_cause": 0.07,
        "duration_cause": 1,
        "title_process": "🎊 活动中心奠基仪式隆重举行",
        "desc_process": "综合活动中心正式奠基动工！设室内篮球馆、专业演播厅、科创工坊，预计一年后投入使用。全板块沸腾！",
        "stocks_affected_process": ALL_STOCKS,
        "impact_process": "bullish", "impact_min_process": 0.10, "impact_max_process": 0.20,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_011",
        "title_cause": "💻 计算机社核心服务器遭遇攻击",
        "desc_cause": "计算机社托管校园服务的服务器遭不明来源DDoS攻击，多个在线系统瘫痪。社团紧急启动应急响应。",
        "stocks_affected_cause": ["computer"],
        "impact_cause": "bearish", "impact_min_cause": -0.10, "impact_max_cause": -0.05,
        "duration_cause": 1,
        "title_process": "🔐 系统恢复并升级安全防护获表彰",
        "desc_process": "计算机社成功抵御攻击并全面升级了安全系统。校方对社团技术应急能力给予表彰，追加网络安全专项经费。",
        "stocks_affected_process": ["computer"],
        "impact_process": "bullish", "impact_min_process": 0.10, "impact_max_process": 0.17,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 2,
    },
    {
        "id": "chain_012",
        "title_cause": "🗳️ 新一届社团联合会主席选举启动",
        "desc_cause": "校社团联合会主席换届选举正式启动，多位候选人宣布参选，各自承诺为不同板块社团争取更多资源。局势未明。",
        "stocks_affected_cause": ALL_STOCKS,
        "impact_cause": "mixed", "impact_min_cause": -0.03, "impact_max_cause": 0.03,
        "duration_cause": 1,
        "title_process": "🎯 新主席上任宣布「社团振兴计划」",
        "desc_process": "新当选社团联合会主席发表就职演说，推出「社团振兴计划」：增加总预算20%、简化活动审批、开辟社团展示专区。",
        "stocks_affected_process": ALL_STOCKS,
        "impact_process": "bullish", "impact_min_process": 0.06, "impact_max_process": 0.12,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_013",
        "title_cause": "🎵 打击乐社核心成员萌生退意",
        "desc_cause": "因学业压力增大，打击乐社多位核心成员在社内会议上表示可能退社。若核心流失，全国展演将受严重影响。",
        "stocks_affected_cause": ["percussion"],
        "impact_cause": "bearish", "impact_min_cause": -0.10, "impact_max_cause": -0.05,
        "duration_cause": 1,
        "title_process": "💪 全员留任！社团调整训练方案获支持",
        "desc_process": "指导教师与社员家长沟通后推出弹性训练方案，兼顾学业与排练。所有核心成员宣布留任，士气大振！",
        "stocks_affected_process": ["percussion"],
        "impact_process": "bullish", "impact_min_process": 0.12, "impact_max_process": 0.20,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 2,
    },
    {
        "id": "chain_014",
        "title_cause": "⚠️ 航模社无人机在市区禁飞区试飞被查处",
        "desc_cause": "航模社社员误入市区禁飞区域试飞无人机，被相关部门查处。校方要求航模社暂停一切户外飞行活动。",
        "stocks_affected_cause": ["aero-model"],
        "impact_cause": "bearish", "impact_min_cause": -0.15, "impact_max_cause": -0.09,
        "duration_cause": 1,
        "title_process": "📋 整改完成！航模社获批专属空域",
        "desc_process": "经整改和安全培训后，航模社获空管部门批准使用学校指定空域，并安装了电子围栏系统确保飞行安全。",
        "stocks_affected_process": ["aero-model"],
        "impact_process": "bullish", "impact_min_process": 0.10, "impact_max_process": 0.16,
        "duration_process": 4,
        "delay_min": 1, "delay_max": 3,
    },
    {
        "id": "chain_015",
        "title_cause": "🌊 辩论社赛前核心辩题准备陷入困境",
        "desc_cause": "市级辩论赛辩题公布，是辩论社从未接触过的「量子计算伦理」话题。队员们束手无策，备赛进度严重滞后。",
        "stocks_affected_cause": ["debate"],
        "impact_cause": "bearish", "impact_min_cause": -0.08, "impact_max_cause": -0.04,
        "duration_cause": 1,
        "title_process": "🧠 变劣势为优势！辩论社科技辩题惊艳全场",
        "desc_process": "辩论社紧急邀请计算机社、超科学社进行科技知识辅导，融合人文与科技视角的辩论方案在半决赛中惊艳评委！",
        "stocks_affected_process": ["debate", "computer"],
        "impact_process": "bullish", "impact_min_process": 0.14, "impact_max_process": 0.22,
        "duration_process": 5,
        "delay_min": 1, "delay_max": 2,
    },
]


# ============================================================
# 合并所有事件为统一列表（向后兼容）
# ============================================================
# EVENTS = SCHEDULED_EVENTS + 每日随机抽取 + 因果关系起因事件
# 主引擎会根据当前天数决定触发哪些事件
# ============================================================

# 将SCHEDULED_EVENTS索引为负数，方便与随机事件区分
# 固定事件: event_index = -(i+1)  (负值)
# 随机/因果事件: event_index = 从大数开始的正值

# 构建完整事件列表
EVENTS = list(SCHEDULED_EVENTS)  # 固定时间线在前
# 注：随机事件和因果事件由 game_engine 动态添加
# EVENTS 列表在运行时会被动态扩展
